spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/taskmanagement
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: false
server:
  port: 8081