spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/taskmanagement
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8081
logging:
  file:
    name: logs/task-log.log
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5relative [%thread] %-5level %logger{35} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-3level-%logger{35}-%msg%n"
#    console: "%(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
security:
  jwt:
    secret-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDevlpBLbDw+wb+3myHhAjjcafDL1SAWjYIzdMsRiirOuBm6kWqZqtxgmyP+
    expiration:
      access-token-time: 3600000
      refresh-token-time: 86400000