spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/taskmanagement
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8081
security:
  jwt:
    secret-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDevlpBLbDw+wb+3myHhAjjcafDL1SAWjYIzdMsRiirOuBm6kWqZqtxgmyP+
    expiration:
      access-token-time: 3600000
angular:
  url: http://localhost:4200